### ISSUE TITLE
Uncaught TypeError: _export is not a function

### ISSUE THREAD

**Issue by ubald** [vazco/universe-ecmascript#2]
When trying, even with the simplest app possible, something like (tested in clietn to get the quick debugger but the same happens on the server):

client/startup.js:

```
import Test from './Test'
const t = new Test();
```

client/Test.js:

```
export default class Test {}
```

I get:

```
Uncaught TypeError: _export is not a function
```

Line numbers are useless since they refer to the map file but it refers to this part:

```
_export("default", Test);
```

in the built Test.js file's `execute` method.

**Comment by cristo-rabani** [comment]
Hello,
Now everything should be good. 
Please check new version 0.6.6 

Thanks for reporting this.
