### ISSUE TITLE
full support for meteor modules syntax

### ISSUE THREAD

**Issue by ready-stone** [vazco/universe-ecmascript#4]
Hello folks from universe,
This package is great even now, when meteor offers own modules.
As I can see modules syntax of imports is almost compatible with this in meteor 1.3 (relative path works well)

I beg you to consider of implementation other differences between this package and meteor 1.3. 
This can be good to provides backwards compatibility for many packages.

**Comment by radekmie** [comment]
We've decided to archive some of our repositories as we are no longer using nor willing to maintain them. Part of this process involves closing related issues and PRs. If you still need help, do contact us on opensource@vazco.eu.
